### ISSUE TITLE
Can't mount Sharepoint

### ISSUE THREAD

**Issue by helmut72** [nextcloud/sharepoint#12] opened 2018-02-01 16:36 UTC
After a lot try and error, I get a "green light" with following parameters:

> host: http://our.sp-server.com/sites/DEP/SUB-DEP
> document library: sites/DEP/SUB-DEP/Seiten/Start.aspx
> 

But when I want to access the folder, only a file will be downloaded with following content:

> {"error":{"code":"-2147024891, System.UnauthorizedAccessException","message":{"lang":"de-DE","value":"Zugriff verweigert. Sie haben keine Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen."}}}

======================

Using a Browser, I can access our SP-Server with this URL:
http://our.sp-server.com/sites/DEP/SUB-DEP/Seiten/Start.aspx

![bildschirmfoto 2018-02-01 um 17 23 48](https://user-images.githubusercontent.com/1388751/35690396-0532e4a4-0776-11e8-82e3-8cc2f6a41b93.png)

Or this URL:
http://our.sp-server.com/sites/DEP/SUB-DEP/ZZ%20Dokumente/Forms/AllItems.aspx

![bildschirmfoto 2018-02-01 um 17 23 27](https://user-images.githubusercontent.com/1388751/35690418-17f4f30c-0776-11e8-9bef-f2e7118df9f1.png)

**Comment by aproposnix** [comment] 2018-02-14 15:10
Duplicate of #3 ?

**Comment by blizzz** [comment] 2018-03-19 16:43
> Zugriff verweigert. Sie haben keine Berechtigung, diesen Vorgang auszuf\u00fchren oder auf diese Ressource zuzugreifen

indicated that the permissions are not sufficient. I guess you verified that? Is there anything else in the nextcloud.log? Or perhaps on SP side?

**Comment by helmut72** [comment] 2018-03-19 17:05
My Browser screenshots shows that my user does have sufficient permissions. The german log entry is from nextcloud.log. I will look into SP logs.

I also have the feeling that my configuration isn't correct. This one:
> host: http://our.sp-server.com/sites/DEP/SUB-DEP
> document library: sites/DEP/SUB-DEP/Seiten/Start.aspx

The example in the README.md is a lot easier but never worked for me. Could there be really so many differences from SP to SP? I'm not a SP guy.

**Comment by blizzz** [comment] 2018-03-19 17:11
the document library should really just be the same of the library. .aspx hints to a webpage. With this host, try "Seiten".

**Comment by blizzz** [comment] 2020-05-14 21:58
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Closed by blizzz** 2020-05-14 21:58 UTC
